# GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  Elastic_config = debug
  Sandbox_config = debug
endif
ifeq ($(config),release)
  Elastic_config = release
  Sandbox_config = release
endif
ifeq ($(config),dist)
  Elastic_config = dist
  Sandbox_config = dist
endif

PROJECTS := Elastic Sandbox

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

Elastic:
ifneq (,$(Elastic_config))
	@echo "==== Building Elastic ($(Elastic_config)) ===="
	@${MAKE} --no-print-directory -C Elastic -f Makefile config=$(Elastic_config)
endif

Sandbox: Elastic
ifneq (,$(Sandbox_config))
	@echo "==== Building Sandbox ($(Sandbox_config)) ===="
	@${MAKE} --no-print-directory -C Sandbox -f Makefile config=$(Sandbox_config)
endif

clean:
	@${MAKE} --no-print-directory -C Elastic -f Makefile clean
	@${MAKE} --no-print-directory -C Sandbox -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo "  dist"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   Elastic"
	@echo "   Sandbox"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"